"preserve_hierarchy": true

files: [
  {
    "source": "/app/src/main/res/values/strings.xml",
    "translation": "/app/src/main/res/values-%two_letters_code%/strings.xml"
  },
  {
    "source": "/app/src/main/res/values/plurals.xml",
    "translation": "/app/src/main/res/values-%two_letters_code%/plurals.xml"
  },
  {
    "source": "/features/shopping_lists/src/main/res/values/strings.xml",
    "translation": "/features/shopping_lists/src/main/res/values-%two_letters_code%/strings.xml"
  }
]
